---
title: "Processing_Data_12-11-20"
output: html_document
---

#calculate the subtraction matrix for the predication on 108 ClearTrial samples
#redo the script for latest version "RMAImport_108CLEARTrial_12-07-20.ppj"
```{r}
#import data
MyData_3h <- read.csv(file="../../Input_Output/Predication/DemographicInformation_RMAImport_DS-VS_36CLEARTrial_ExcludeLessThanOrEqualTo3_Exclude_x_atAnd_s_at_3hrForGE_12-30-20_SentToBodie_01-02-2021.txt", header=TRUE, sep="\t", stringsAsFactors = FALSE, check.names=FALSE) #36 28919


MyData_5h <- read.csv(file="../../Input_Output/Predication/DemographicInformation_RMAImport_DS-VS_36CLEARTrial_ExcludeLessThanOrEqualTo3_Exclude_x_atAnd_s_at_5hrForGE_12-30-20_SentToBodie_01-02-2021.txt", header=TRUE, sep="\t", stringsAsFactors = FALSE, check.names=FALSE) #36 28919

MyData_24h <- read.csv(file="../../Input_Output/Predication/DemographicInformation_RMAImport_DS-VS_36CLEARTrial_ExcludeLessThanOrEqualTo3_Exclude_x_atAnd_s_at_24hrForGE_12-30-20_SentToBodie_01-02-2021.txt", header=TRUE, sep="\t", stringsAsFactors = FALSE, check.names=FALSE) #36 28919

```

```{r}
#x <- colnames(MyData_3h)
#y <- colnames(MyData_5h)
#z <- colnames(MyData_24h)

setdiff(x,y)
#character(0)
setdiff(x,z)
#character(0)
setdiff(y,z)
#character(0)
```


```{r}
threehrsubtractfivehr <- MyData_3h[,c(234:28919)] - MyData_5h[,c(234:28919)] #36 28686
rownames(threehrsubtractfivehr) <- MyData_3h$Filename
```
```{r}
#save
save(threehrsubtractfivehr, file = "../../Input_Output/Predication/RData/3hrSubtract5hr_GE_01-04-2021.RData")
write.csv(threehrsubtractfivehr,file = "../../Input_Output/Predication/3hrSubtract5hr_GE_01-04-2021.csv", col.names = T, sep = "\t")
```

```{r}
#We decided to do subtraction in this way (newer-older) since 04-28-2021
fivehrsubtractthreehr <- MyData_5h[,c(234:28919)] - MyData_3h[,c(234:28919)] #36 28686
rownames(fivehrsubtractthreehr) <- MyData_3h$Filename
```

```{r}
#save
save(fivehrsubtractthreehr, file = "../../Input_Output/Predication/RData/5hrSubtract3hr_GE_04-28-2021.RData")
write.csv(fivehrsubtractthreehr,file = "../../Input_Output/Predication/5hrSubtract3hr_GE_04-28-2021.csv", col.names = T, sep = "\t")
```

```{r}
threehrsubtracttwentyFourhr <- MyData_3h[,c(234:28919)] - MyData_24h[,c(234:28919)] #36 28686
rownames(threehrsubtracttwentyFourhr) <- MyData_3h$Filename
```

```{r}
#save
save(threehrsubtracttwentyFourhr, file = "../../Input_Output/Predication/RData/3hrSubtract24hr_GE_01-04-2021.RData")
write.csv(threehrsubtracttwentyFourhr,file = "../../Input_Output/Predication/3hrSubtract24hr_GE_01-04-2021.csv", col.names = T, sep = "\t")
```

```{r}
twentyFourhrsubtractthree <- MyData_24h[,c(234:28919)] - MyData_3h[,c(234:28919)] #36 28686
rownames(twentyFourhrsubtractthree) <- MyData_3h$Filename
```

```{r}
#save
save(twentyFourhrsubtractthree, file = "../../Input_Output/Predication/RData/24hrSubtract3hr_GE_05-03-2021.RData")
write.csv(twentyFourhrsubtractthree,file = "../../Input_Output/Predication/24hrSubtract3hr_GE_05-03-2021.csv", col.names = T, sep = "\t")
```

```{r}
FivehrsubtracttwentyFourhr <- MyData_5h[,c(234:28919)] - MyData_24h[,c(234:28919)] #36 28686
rownames(FivehrsubtracttwentyFourhr) <- MyData_3h$Filename
```

```{r}
#save
save(FivehrsubtracttwentyFourhr, file = "../../Input_Output/Predication/RData/5hrSubtract24hr_GE_01-04-2021.RData")
write.csv(FivehrsubtracttwentyFourhr,file = "../../Input_Output/Predication/5hrSubtract24hr_GE_01-04-2021.csv", col.names = T, sep = "\t")
```

```{r}
twentyFourhrsubtractFivehr <- MyData_24h[,c(234:28919)] - MyData_5h[,c(234:28919)] #36 28686
rownames(twentyFourhrsubtractFivehr) <- MyData_3h$Filename
```

```{r}
#save
save(twentyFourhrsubtractFivehr, file = "../../Input_Output/Predication/RData/24hrSubtract5hr_GE_05-03-2021.RData")
write.csv(twentyFourhrsubtractFivehr,file = "../../Input_Output/Predication/24hrSubtract5hr_GE_05-03-2021.csv", col.names = T, sep = "\t")
```

```{r}
#With Internal Gene Normalized value
MyData_3h <- read.csv(file="../../Input_Output/Predication/IntNormGene/RMAimport36CLEARTrial_V4_GeoMeanOf38MostStableProbeset_DividedByGeoMeanOf38MostStableProbeset_11-30-20_Exclude_x_atAnd_s_at_Only3hGE_04-12-2021.csv", header=TRUE, sep=",", stringsAsFactors = FALSE, check.names=FALSE) #36 39308

MyData_24h <- read.csv(file="../../Input_Output/Predication/IntNormGene/RMAimport36CLEARTrial_V4_GeoMeanOf38MostStableProbeset_DividedByGeoMeanOf38MostStableProbeset_11-30-20_Exclude_x_atAnd_s_at_Only24hGE_04-02-2021.csv", header=TRUE, sep=",", stringsAsFactors = FALSE, check.names=FALSE) #36 39308
```

```{r}
#With Internal Gene Normalized value
twentyFourhrsubtractthree <- MyData_24h[,c(234:39308)] - MyData_3h[,c(234:39308)] #36 39075
rownames(twentyFourhrsubtractthree) <- MyData_3h$Filename
```

```{r}
#save
save(twentyFourhrsubtractthree, file = "../../Input_Output/Predication/RData/IntNormGene/24hrSubtract3hr_GE_05-04-2021.RData")
write.csv(twentyFourhrsubtractthree,file = "../../Input_Output/Predication/IntNormGene/24hrSubtract3hr_GE_05-04-2021.csv", col.names = T, sep = "\t")
```


```{r}
#With RMA value For Biology Part
MyData_3h <- read.csv(file="../../Input_Output/Biology_Part/RMAimport_108CLEARTrialAnd18SAVVYSamples_ExcludeLessThanOrEqualTo3_05-10-2021_3hrGE_05-11-2021.csv", header=TRUE, sep=",", stringsAsFactors = FALSE, check.names=FALSE) #36 43923

MyData_24h <- read.csv(file="../../Input_Output/Biology_Part/RMAimport_108CLEARTrialAnd18SAVVYSamples_ExcludeLessThanOrEqualTo3_05-10-2021_24hrGE_05-11-2021.csv", header=TRUE, sep=",", stringsAsFactors = FALSE, check.names=FALSE) #36 43923
```

```{r}
twentyFourhrsubtractthree <- MyData_24h[,c(234:43923)] - MyData_3h[,c(234:43923)] #36 43690
rownames(twentyFourhrsubtractthree) <- MyData_3h$Filename
```

```{r}
#save
save(twentyFourhrsubtractthree, file = "../../Input_Output/Biology_Part/RData/24hrSubtract3hr_GE_05-27-2021.RData")
write.csv(twentyFourhrsubtractthree,file = "../../Input_Output/Biology_Part/24hrSubtract3hr_GE_05-27-2021.csv", col.names = T, sep = "\t")
```